{
 "title": "Highload-3",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk IOps back-1",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"5.188.142.220:9100\", job=\"blackback-1-server\", device=\"sr0\"}[$__rate_interval])"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"5.188.142.220:9100\", job=\"blackback-1-server\", device=\"vda\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "CPU Busy back-1",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"5.188.142.220:9100\",job=\"blackback-1-server\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"5.188.142.220:9100\",job=\"blackback-1-server\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"5.188.142.220:9100\",job=\"blackback-1-server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Backend-1 Sys Load (1m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"5.188.142.220:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.142.220:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-1 Sys Load (5m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"5.188.142.220:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.142.220:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-1 Sys Load (15m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"5.188.142.220:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.142.220:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-2 Sys Load (1m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"89.208.229.114:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"89.208.229.114:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-2 Sys Load (5m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"89.208.229.114:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"89.208.229.114:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-2 Sys Load (15m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"89.208.229.114:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"89.208.229.114:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-3 Sys Load (1m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"5.188.143.20:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.143.20:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-3 Sys Load (5m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"5.188.143.20:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.143.20:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Backend-3 Sys Load (15m avg)",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"5.188.143.20:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"5.188.143.20:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Disk IOps 2",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"89.208.229.114:9100\", job=\"blackback-2-server\", device=\"sr0\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "CPU Busy back-2",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 13, "w": 4, "x": 5, "y": 13 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"89.208.229.114:9100\",job=\"blackback-2-server\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"89.208.229.114:9100\",job=\"blackback-2-server\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"89.208.229.114:9100\",job=\"blackback-2-server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RPS Success",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "expr": "rate(forum{code=\"200\",method=\"GET\",url=\"/api/service/status\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk IOps 3",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"5.188.143.20:9100\", job=\"blackback-3-server\", device=\"sr0\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "CPU Busy back-3",
   "type": "timeseries",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 14, "w": 5, "x": 5, "y": 26 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"5.188.143.20:9100\",job=\"blackback-3-server\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode=\"idle\",instance=\"5.188.143.20:9100\",job=\"blackback-3-server\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"5.188.143.20:9100\",job=\"blackback-3-server\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "backends RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 29 },
   "targets": [
    {
     "expr": "rate(hits{url=\"/api/service/status\", instance=\"5.188.143.20:5000\"}[10s])"
    },
    {
     "expr": "rate(hits{url=\"/api/service/status\", instance=\"89.208.229.114:5000\"}[10s])"
    },
    {
     "expr": "rate(hits{url=\"/api/service/status\", instance=\"5.188.142.220:5000\"}[10s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(durations_stats_bucket[5m])) by (le)) "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(durations_stats_bucket[5m])) by (le)) "
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(durations_stats_bucket[5m])) by (le)) "
    }
   ]
  }
 ]
}