global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  # LOAD BALANCER
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackback-balancer-server'
    static_configs:
      - targets: ['node_exporter:9100']

  # SERVERS

  # SERVER 1
  - job_name: 'blackback-1-backend'
    static_configs:
      - targets: ['5.188.142.220:5000']

  - job_name: 'blackback-1-server'
    static_configs:
      - targets: ['5.188.142.220:9100']

  # SERVER 2
  - job_name: 'blackback-2-backend'
    static_configs:
      - targets: ['89.208.229.114:5000']

  - job_name: 'blackback-2-server'
    static_configs:
      - targets: ['89.208.229.114:9100']

  # SERVER 3
  - job_name: 'blackback-3-backend'
    static_configs:
      - targets: ['5.188.143.20:5000']

  - job_name: 'blackback-3-server'
    static_configs:
      - targets: ['5.188.143.20:9100']